site_name: BH Spectra
docs_dir: docs
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.top
    - content.code.copy
  palette:
    - scheme: slate
      primary: blue
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: default
      primary: blue
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
plugins:
  - search
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
extra_css:
  - stylesheets/jupyter.css
extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
nav:
  - Home: index.md
  - Physics: physics.md
  - Docs how-to: docshowto.md
