site_name: BH Molecule
docs_dir: docs
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - content.code.copy
  palette:
    - scheme: bh-dark
      primary: custom
      accent: yellow
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: default
      primary: amber
      accent: red
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
plugins:
  - search
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - mdx_truly_sane_lists:
      nested_indent: 4
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - styles/brand.css
nav:
  - Home: index.md
  - Physics: physics.md
  - CLI: cli_commands.md
  - Dev Install Guide: dev-install-guide.md
  - Venv: venv-outside-synced-folders.md